// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen() {
  return window['go']['main']['App']['CaptureScreen']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearState() {
  return window['go']['main']['App']['ClearState']();
}

export function DeleteCacheItems(arg1) {
  return window['go']['main']['App']['DeleteCacheItems'](arg1);
}

export function DeleteToken() {
  return window['go']['main']['App']['DeleteToken']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCacheItems() {
  return window['go']['main']['App']['GetCacheItems']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetMachineId() {
  return window['go']['main']['App']['GetMachineId']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadToken() {
  return window['go']['main']['App']['LoadToken']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}

export function SetAudioDevice(arg1, arg2) {
  return window['go']['main']['App']['SetAudioDevice'](arg1, arg2);
}

export function SetClickthrough(arg1) {
  return window['go']['main']['App']['SetClickthrough'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}

export function StopBackend() {
  return window['go']['main']['App']['StopBackend']();
}

export function ToggleStealth(arg1) {
  return window['go']['main']['App']['ToggleStealth'](arg1);
}
