// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeVision(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeVision'](arg1, arg2);
}

export function CaptureScreen() {
  return window['go']['main']['App']['CaptureScreen']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearState() {
  return window['go']['main']['App']['ClearState']();
}

export function CloseDocument(arg1) {
  return window['go']['main']['App']['CloseDocument'](arg1);
}

export function DeleteCacheItems(arg1) {
  return window['go']['main']['App']['DeleteCacheItems'](arg1);
}

export function DeleteToken() {
  return window['go']['main']['App']['DeleteToken']();
}

export function EndSession() {
  return window['go']['main']['App']['EndSession']();
}

export function GetActiveDocument() {
  return window['go']['main']['App']['GetActiveDocument']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCacheItems() {
  return window['go']['main']['App']['GetCacheItems']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetIDEState() {
  return window['go']['main']['App']['GetIDEState']();
}

export function GetMachineId() {
  return window['go']['main']['App']['GetMachineId']();
}

export function GetOpenDocuments() {
  return window['go']['main']['App']['GetOpenDocuments']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetWorkspaceTree() {
  return window['go']['main']['App']['GetWorkspaceTree']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadToken() {
  return window['go']['main']['App']['LoadToken']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PromptOpenDirectory() {
  return window['go']['main']['App']['PromptOpenDirectory']();
}

export function PromptOpenFile() {
  return window['go']['main']['App']['PromptOpenFile']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}

export function SetActiveDocument(arg1) {
  return window['go']['main']['App']['SetActiveDocument'](arg1);
}

export function SetAudioDevice(arg1, arg2) {
  return window['go']['main']['App']['SetAudioDevice'](arg1, arg2);
}

export function SetClickthrough(arg1) {
  return window['go']['main']['App']['SetClickthrough'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}

export function StopBackend() {
  return window['go']['main']['App']['StopBackend']();
}

export function ToggleClickthroughMode() {
  return window['go']['main']['App']['ToggleClickthroughMode']();
}

export function ToggleStealth(arg1) {
  return window['go']['main']['App']['ToggleStealth'](arg1);
}
