// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';

export function CaptureScreen():Promise<string>;

export function DeleteToken():Promise<void>;

export function GetAudioDevices():Promise<Array<audio.AudioDevice>>;

export function GetMachineId():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadToken():Promise<string>;

export function QuitApp():Promise<void>;

export function SaveToken(arg1:Record<string, any>):Promise<void>;

export function SetAudioDevice(arg1:number,arg2:boolean):Promise<void>;

export function SetClickthrough(arg1:Record<string, any>):Promise<void>;

export function StartBackend():Promise<void>;

export function StopBackend():Promise<void>;

export function ToggleStealth(arg1:Record<string, any>):Promise<void>;
