// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AnalyzeVision(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeVision'](arg1, arg2);
}

export function AppendToBuffer(arg1) {
  return window['go']['main']['App']['AppendToBuffer'](arg1);
}

export function CaptureScreen() {
  return window['go']['main']['App']['CaptureScreen']();
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearState() {
  return window['go']['main']['App']['ClearState']();
}

export function CloseDocument(arg1) {
  return window['go']['main']['App']['CloseDocument'](arg1);
}

export function DeactivateLicense() {
  return window['go']['main']['App']['DeactivateLicense']();
}

export function DeleteCacheItems(arg1) {
  return window['go']['main']['App']['DeleteCacheItems'](arg1);
}

export function DeleteToken() {
  return window['go']['main']['App']['DeleteToken']();
}

export function EndSession() {
  return window['go']['main']['App']['EndSession']();
}

export function ExportSession() {
  return window['go']['main']['App']['ExportSession']();
}

export function FlushQuestionBuffer() {
  return window['go']['main']['App']['FlushQuestionBuffer']();
}

export function GetActiveDocument() {
  return window['go']['main']['App']['GetActiveDocument']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCacheItems() {
  return window['go']['main']['App']['GetCacheItems']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetIDEState() {
  return window['go']['main']['App']['GetIDEState']();
}

export function GetIndexedPaths() {
  return window['go']['main']['App']['GetIndexedPaths']();
}

export function GetMachineId() {
  return window['go']['main']['App']['GetMachineId']();
}

export function GetOpenDocuments() {
  return window['go']['main']['App']['GetOpenDocuments']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function GetWorkspaceTree() {
  return window['go']['main']['App']['GetWorkspaceTree']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideFromTaskbar() {
  return window['go']['main']['App']['HideFromTaskbar']();
}

export function IndexFile(arg1) {
  return window['go']['main']['App']['IndexFile'](arg1);
}

export function IndexFolder(arg1) {
  return window['go']['main']['App']['IndexFolder'](arg1);
}

export function LoadToken() {
  return window['go']['main']['App']['LoadToken']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PromptOpenDirectory() {
  return window['go']['main']['App']['PromptOpenDirectory']();
}

export function PromptOpenFile() {
  return window['go']['main']['App']['PromptOpenFile']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveIndexedPath(arg1) {
  return window['go']['main']['App']['RemoveIndexedPath'](arg1);
}

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetActiveDocument(arg1) {
  return window['go']['main']['App']['SetActiveDocument'](arg1);
}

export function SetAudioDevice(arg1, arg2) {
  return window['go']['main']['App']['SetAudioDevice'](arg1, arg2);
}

export function SetClickthrough(arg1) {
  return window['go']['main']['App']['SetClickthrough'](arg1);
}

export function SetIncludeActiveDocContext(arg1) {
  return window['go']['main']['App']['SetIncludeActiveDocContext'](arg1);
}

export function SetManualMode(arg1) {
  return window['go']['main']['App']['SetManualMode'](arg1);
}

export function SetProxyToken(arg1) {
  return window['go']['main']['App']['SetProxyToken'](arg1);
}

export function SetRawMode(arg1) {
  return window['go']['main']['App']['SetRawMode'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}

export function StartOAuthFlow(arg1) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1);
}

export function StopBackend() {
  return window['go']['main']['App']['StopBackend']();
}

export function SummarizeSession(arg1) {
  return window['go']['main']['App']['SummarizeSession'](arg1);
}

export function ToggleClickthroughMode() {
  return window['go']['main']['App']['ToggleClickthroughMode']();
}

export function ToggleMic() {
  return window['go']['main']['App']['ToggleMic']();
}

export function ToggleMockInterviewMode(arg1) {
  return window['go']['main']['App']['ToggleMockInterviewMode'](arg1);
}

export function ToggleStealth(arg1) {
  return window['go']['main']['App']['ToggleStealth'](arg1);
}
