// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {driving} from '../models';
import {audio} from '../models';
import {backend} from '../models';
import {engine} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function AnalyzeVision(arg1:string,arg2:string):Promise<void>;

export function AppendToBuffer(arg1:string):Promise<void>;

export function CaptureScreen():Promise<string>;

export function CheckLicense():Promise<string>;

export function ClearCache():Promise<void>;

export function ClearState():Promise<void>;

export function CloseDocument(arg1:string):Promise<void>;

export function DeactivateLicense():Promise<void>;

export function DeleteCacheItems(arg1:Array<string>):Promise<void>;

export function DeleteToken():Promise<void>;

export function EndSession():Promise<Record<string, any>>;

export function ExportSession():Promise<string>;

export function FlushQuestionBuffer():Promise<void>;

export function GetActiveDocument():Promise<driving.WorkspaceDocument>;

export function GetAudioDevices():Promise<Array<audio.AudioDevice>>;

export function GetCacheItems():Promise<Array<backend.CacheItem>>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetIDEState():Promise<Record<string, any>>;

export function GetIndexedPaths():Promise<Array<string>>;

export function GetMachineId():Promise<string>;

export function GetOpenDocuments():Promise<Array<driving.WorkspaceDocument>>;

export function GetState():Promise<Record<string, any>>;

export function GetSystemStatus():Promise<Record<string, string>>;

export function GetWorkspaceTree():Promise<Array<driving.FileNode>>;

export function Greet(arg1:string):Promise<string>;

export function HideFromTaskbar():Promise<void>;

export function IndexFile(arg1:string):Promise<void>;

export function IndexFolder(arg1:string):Promise<void>;

export function LoadToken():Promise<string>;

export function OpenDirectory(arg1:string):Promise<driving.FileNode>;

export function OpenFile(arg1:string):Promise<driving.WorkspaceDocument>;

export function PromptOpenDirectory():Promise<string>;

export function PromptOpenFile():Promise<string>;

export function QuitApp():Promise<void>;

export function RemoveIndexedPath(arg1:string):Promise<void>;

export function SaveToken(arg1:Record<string, any>):Promise<void>;

export function SendChat(arg1:string):Promise<void>;

export function SetActiveDocument(arg1:string):Promise<void>;

export function SetAudioDevice(arg1:number,arg2:boolean):Promise<void>;

export function SetClickthrough(arg1:boolean):Promise<void>;

export function SetIncludeActiveDocContext(arg1:boolean):Promise<void>;

export function SetManualMode(arg1:boolean):Promise<void>;

export function SetProxyToken(arg1:string):Promise<void>;

export function SetRawMode(arg1:boolean):Promise<void>;

export function StartBackend():Promise<void>;

export function StartOAuthFlow(arg1:string):Promise<void>;

export function StopBackend():Promise<void>;

export function SummarizeSession(arg1:Array<engine.SummaryRequest>):Promise<void>;

export function ToggleClickthroughMode():Promise<boolean>;

export function ToggleMic():Promise<boolean>;

export function ToggleMockInterviewMode(arg1:boolean):Promise<void>;

export function ToggleStealth(arg1:Record<string, any>):Promise<void>;
