// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskQuestion(arg1) {
  return window['go']['presenter']['PresenterApp']['AskQuestion'](arg1);
}

export function ClearState() {
  return window['go']['presenter']['PresenterApp']['ClearState']();
}

export function GetState() {
  return window['go']['presenter']['PresenterApp']['GetState']();
}

export function LoadDocument(arg1) {
  return window['go']['presenter']['PresenterApp']['LoadDocument'](arg1);
}
