// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {driving} from '../models';

export function AskQuestion(arg1:string):Promise<void>;

export function ClearState():Promise<void>;

export function CloseFile(arg1:string):Promise<void>;

export function GetState():Promise<Record<string, any>>;

export function GetWorkspaceTree():Promise<Array<driving.FileNode>>;

export function LoadDocument(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<driving.WorkspaceDocument>;

export function PromptLoadDocument():Promise<string>;

export function PromptOpenDirectory():Promise<driving.FileNode>;

export function PromptOpenFile():Promise<driving.WorkspaceDocument>;

export function SetActiveDocument(arg1:string):Promise<driving.WorkspaceDocument>;
