// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskQuestion(arg1:string):Promise<void>;

export function ClearState():Promise<void>;

export function GetState():Promise<Record<string, any>>;

export function LoadDocument(arg1:string):Promise<string>;

export function PromptLoadDocument():Promise<string>;
